import numpy as np
import matplotlib.pyplot as plt

def f_q(z, q):
    return 1 + q / (z - 1)

def quantize(z, eps):
    return (
        np.round(z.real / eps).astype(np.int64),
        np.round(z.imag / eps).astype(np.int64)
    )



def build_generated_shape(
    q,
    steps=30,
    eps=1e-2,
    max_abs=5,
    pair_chunk=300_000,
    pole_tol=1e-10,
    verbose=True,
    break_on_escape=True
):
    """
    Approximate the limiting generated set by binning points onto an eps-grid.

    V_0 = {0}
    V_{n+1} = V_n union V_n^2 union f_q(V_n)

    where V_n^2 = {v*w : v,w in V_n}.

    The function returns escaped=True if either:
      1. a generated point satisfies |z| > max_abs, or
      2. the eps-grid cell containing 1-q is generated by a product,
         i.e. 1-q is detected in V^2.

    The check for 1-q is only applied to the product step, not to f_q(V).
    """

    q = complex(q)

    keys = set()
    escaped = False
    escaped_point = None
    escaped_reason = None

    # Target value: 1-q
    target = 1 - q
    target_kr, target_ki = quantize(np.array([target], dtype=complex), eps)
    target_key = (int(target_kr[0]), int(target_ki[0]))

    def add_points(arr, check_target=False):
        nonlocal escaped, escaped_point, escaped_reason

        arr = np.asarray(arr, dtype=complex).ravel()

        finite_mask = (
            np.isfinite(arr.real)
            & np.isfinite(arr.imag)
        )
        arr = arr[finite_mask]

        if len(arr) == 0:
            return np.array([], dtype=complex)

        kr, ki = quantize(arr, eps)

        # Check whether 1-q is in the generated product set V^2.
        # This is only used when check_target=True.
        if check_target:
            for z, a, b in zip(arr, kr, ki):
                key = (int(a), int(b))
                if key == target_key:
                    escaped = True
                    escaped_point = z
                    escaped_reason = "hit 1-q in V^2"
                    return np.array([], dtype=complex)

        new = []
        for z, a, b in zip(arr, kr, ki):
            key = (int(a), int(b))

            # Check escape by size.
            if abs(z) > max_abs:
                if break_on_escape:
                    escaped = True
                    escaped_point = z
                    escaped_reason = "escaped max_abs"
                    return np.array([], dtype=complex)
                else:
                    continue

            if key not in keys:
                keys.add(key)
                new.append(eps * (a + 1j * b))

        return np.array(new, dtype=complex)

    # Initial set V_0 = {0}
    points = add_points(np.array([0 + 0j]), check_target=False)
    frontier = points.copy()
    history = [points.copy()]

    # Optional: check whether 1-q is already in V_0^2 = {0}.
    # This only matters when q = 1.
    if target_key in keys:
        escaped = True
        escaped_point = 0 + 0j
        escaped_reason = "hit 1-q in V_0^2"

        if verbose:
            print(
                f"Stopped immediately: {escaped_reason}. "
                f"point = {escaped_point}"
            )

        return points, history, escaped

    for step in range(1, steps + 1):
        old_points = points.copy()
        new_step = []

        if len(frontier) == 0:
            break

        rows_per_chunk = max(1, pair_chunk // max(1, len(old_points)))

        for start in range(0, len(frontier), rows_per_chunk):
            X = frontier[start:start + rows_per_chunk]

            # Operation 1: all products x*y.
            # This is the only place where we check whether 1-q lies in V^2.
            prod = X[:, None] * old_points[None, :]
            new_prod = add_points(prod, check_target=True)

            if escaped:
                if verbose:
                    print(
                        f"Stopped at step {step}: {escaped_reason}. "
                        f"point = {escaped_point}"
                    )
                return points, history, escaped

            if len(new_prod) > 0:
                new_step.append(new_prod)

            # Operation 2: f_q(x).
            # Do not check for 1-q here, because this is f_q(V), not V^2.
            valid_X = np.abs(X - 1) > pole_tol
            X_safe = X[valid_X]

            if len(X_safe) > 0:
                f_X = f_q(X_safe, q)
                new_f = add_points(f_X, check_target=False)

                if escaped:
                    if verbose:
                        print(
                            f"Stopped at step {step}: {escaped_reason}. "
                            f"point = {escaped_point}"
                        )
                    return points, history, escaped

                if len(new_f) > 0:
                    new_step.append(new_f)

        if len(new_step) == 0:
            if verbose:
                print("No new grid cells added. Shape stabilized numerically.")
            break

        frontier = np.concatenate(new_step)
        points = np.concatenate([points, frontier])
        history.append(points.copy())

        if verbose:
            print(
                f"Step {step}: cells = {len(points)}, "
                f"new cells = {len(frontier)}"
            )

    # If we used all steps without stabilization, regard this as no convergence yet.
    if step == steps:
        return points, history, True

    return points, history, escaped


def T_q(z, q):
    a = np.sqrt(q)
    return (z - (1 + a)) / (z - (1 - a))

def plot_shape_f_and_T(points, q, plot_radius=None, T_plot_radius=10, pole_tol=1e-10):
    fig, axes = plt.subplots(1, 3, figsize=(21, 7))

    theta = np.linspace(0, 2*np.pi, 1000)
    unit_circle = np.exp(1j * theta)

    # ------------------
    # Plot V
    # ------------------
    axes[0].scatter(points.real, points.imag, s=2)
    axes[0].plot(unit_circle.real, unit_circle.imag, linewidth=1.5, label=r"$|z|=1$")
    axes[0].axhline(0, linewidth=0.5)
    axes[0].axvline(0, linewidth=0.5)
    axes[0].set_title(r"Approximate generated shape $V$")
    axes[0].set_xlabel("Re")
    axes[0].set_ylabel("Im")
    axes[0].axis("equal")
    axes[0].legend()

    # ------------------
    # Plot f_q(V)
    # ------------------
    valid = np.abs(points - 1) > pole_tol
    fpoints = f_q(points[valid], q)

    if plot_radius is not None:
        fpoints = fpoints[np.abs(fpoints) <= plot_radius]

    axes[1].scatter(fpoints.real, fpoints.imag, s=2)
    axes[1].plot(unit_circle.real, unit_circle.imag, linewidth=1.5, label=r"$|z|=1$")
    axes[1].axhline(0, linewidth=0.5)
    axes[1].axvline(0, linewidth=0.5)
    axes[1].set_title(r"Image $f_q(V)$")
    axes[1].set_xlabel("Re")
    axes[1].set_ylabel("Im")
    axes[1].axis("equal")
    axes[1].legend()

    # ------------------
    # Plot T(V)
    # ------------------
    a = np.sqrt(q)
    fixed_minus = 1 - a

    valid_T = np.abs(points - fixed_minus) > pole_tol
    Tpoints = T_q(points[valid_T], q)

    Tpoints = Tpoints[
        np.isfinite(Tpoints.real)
        & np.isfinite(Tpoints.imag)
        & (np.abs(Tpoints) <= T_plot_radius)
    ]

    axes[2].scatter(Tpoints.real, Tpoints.imag, s=2)
    axes[2].plot(unit_circle.real, unit_circle.imag, linewidth=1.5, label=r"$|w|=1$")
    axes[2].axhline(0, linewidth=0.5)
    axes[2].axvline(0, linewidth=0.5)
    axes[2].set_title(r"Transformed set $T(V)$")
    axes[2].set_xlabel("Re")
    axes[2].set_ylabel("Im")
    axes[2].axis("equal")
    axes[2].legend()

    if plot_radius is not None:
        for ax in axes[:2]:
            ax.set_xlim(-plot_radius, plot_radius)
            ax.set_ylim(-plot_radius, plot_radius)

    if T_plot_radius is not None:
        axes[2].set_xlim(-T_plot_radius, T_plot_radius)
        axes[2].set_ylim(-T_plot_radius, T_plot_radius)

    fig.suptitle(f"q = {q}")
    plt.tight_layout()
    plt.show()



if __name__ == "__main__":
    q = 2

    points, history, escaped = build_generated_shape(q, 300, 1e-2, 1.2, verbose=True)
    print(escaped)
    plot_shape_f_and_T(points, q, plot_radius=3)